name: Build
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
  push:
    branches: [ main ]
  schedule:
    # Run a build once per week on the main branch.
    - cron: "0 0 * * 0"

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    permissions:
      actions: read
      checks: write
      contents: read
      pull-requests: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Needed to keep actions working correctly.
          fetch-depth: 2

      - name: Initialize JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Compile and run tests
        run: >-
          ./mvnw
          -B 
          -U
          -T8C
          --no-transfer-progress
          '-Dcheckstyle.skip=true'
          '-Dstyle.color=always'
          '-Dmaven.artifact.threads=50'
          clean package
          
      - name: Publish to codecov
        continue-on-error: true
        if: always()
        run: bash <(curl -s https://codecov.io/bash)

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        continue-on-error: true
        with:
          junit_files: "**/target/**/TEST-*.xml"

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        continue-on-error: true

      - name: Perform Checkstyle Analysis
        if: always()
        run: ./mvnw
          -B 
          -U
          -T8C
          --no-transfer-progress
          '-Dstyle.color=always'
          '-Dmaven.artifact.threads=50'
          checkstyle
